version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.24
    restart: always
    ports:
    - "${PRISMA_API_PORT}:${PRISMA_API_PORT}"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: $DATABASE_HOST
            database: $DATABASE
            user: $DATABASE_USER
            password: $DATABASE_PASSWORD
            rawAccess: true
            port: $DATABASE_PORT
            migrations: true
